name: Build

# Controls when the workflow will run
on: [workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  buildArm:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Runs a set of commands using the runners shell
      - name: Setup
        run: |
          sudo apt update -y
          sudo apt upgrade -y
          sudo apt install make -y
          sudo apt install clang -y
          sudo apt install build-essential -y
          sudo apt install zip -y
          sudo apt install gcc-multilib -y

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r21e
          
      - name: Build
        run: |
          sudo chmod -R 777 /home/runner/work/luajit/ 
          ./mk-luajit.sh armeabi-v7a

      - uses: actions/upload-artifact@v2
        with:
          name: luajit-arm
          path: luajit

  buildArm64:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a set of commands using the runners shell
      - name: Setup
        run: |
          sudo apt update -y
          sudo apt upgrade -y
          sudo apt install make -y
          sudo apt install clang -y
          sudo apt install build-essential -y
          sudo apt install zip -y
          sudo apt install gcc-multilib -y

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r21e
          
      - name: Build
        run: |
          sudo chmod -R 777 ./
          ./mk-luajit.sh arm64-v8a

      - uses: actions/upload-artifact@v2
        with:
          name: luajit-arch64
          path: luajit

  # This workflow contains a single job called "build"
  buildx86:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a set of commands using the runners shell
      - name: Setup
        run: |
          sudo apt update -y
          sudo apt upgrade -y
          sudo apt install make -y
          sudo apt install clang -y
          sudo apt install build-essential -y
          sudo apt install zip -y
          sudo apt install gcc-multilib -y

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r21e
          
      - name: Build
        run: |
          sudo chmod -R 777 ./
          ./mk-luajit.sh x86

      - uses: actions/upload-artifact@v2
        with:
          name: luajit-x86
          path: luajit

  # This workflow contains a single job called "build"
  buildx86_64:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a set of commands using the runners shell
      - name: Setup
        run: |
          sudo apt update -y
          sudo apt upgrade -y
          sudo apt install make -y
          sudo apt install clang -y
          sudo apt install build-essential -y
          sudo apt install zip -y
          sudo apt install gcc-multilib -y
         
      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r21e
          
      - name: Build
        run: |
          sudo chmod -R 777 ./
          ./mk-luajit.sh x86_64

      - uses: actions/upload-artifact@v2
        with:
          name: luajit-x86_64
          path: luajit

  build-windows:
    # The type of runner that the job will run on
    runs-on: windows-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a set of commands using the runners shell

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1
          
      - name: Build
        run: |
          cd luajit/src
          ./msvcbuild.bat

      - uses: actions/upload-artifact@v2
        with:
          name: luajit-windows
          path: luajit

  build-linux-64:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a set of commands using the runners shell
      - name: Setup
        run: |
          sudo apt update -y
          sudo apt upgrade -y
          sudo apt install make -y
          sudo apt install clang -y
          sudo apt install build-essential -y

      - name: Build
        run: |
          cd luajit/luajit
          make

      - uses: actions/upload-artifact@v2
        with:
          name: luajit-linux
          path: luajit
